### ISSUE TITLE
Random color

### ISSUE THREAD

**Issue by hesting15** [rsbondi/highlight-words#10]
Thanks for this plug-in! Use it all the time!

There is one thing I would like to have though: if word is already highlighted, applying `addHighlight` again changes color to the next one. Ideally to a random color, not predefined. In this case I would press `addHighlight` few times to get a color I like.

Thanks!

**Comment by rsbondi** [comment]
Thanks for the suggestion.  This seems beyond the intention of this plugin.  I am also considering changing the `addHighlight` to a `toggleHighlight`, which would give an easier way to remove a highlight, and this operation would be in conflict.
