### ISSUE TITLE
defaultMode setting is ignored

### ISSUE THREAD

**Issue by karel-dolezal** [rsbondi/highlight-words#12]
Thank you for a great plugin! :+1: 

The `default highlight` mode is never loaded from my settings, though. Other settings like custom color are loaded ok. I suspect a bug, but I might be just doing something wrong. What I want to do is to use "whole word" mode in any and all files and projects without manually switching it.

The content of my `~/.config/Code/User/settings.json` is:
```
{
    "highlightwords.colors": [
        { "light": "#d1e0e0", "dark": "red" },
        { "light": "#ffb3ff", "dark": "cornflowerblue" },
        { "light": "#b3ffb3", "dark": "orange" },
        { "light": "#ffd9b3", "dark": "magenta" },
        { "light": "#b3d9ff", "dark": "cyan" },
        { "light": "#b3b3ff", "dark": "lightgreen" },
        { "light": "#e6ffb3", "dark": "pink" },
        { "light": "#ffff80", "dark": "green" },
    ],
    "highlightwords.defaultMode": {
        "default": 1
    }
}
```

**Comment by karel-dolezal** [comment]
Looks like it "sort of" works if I use `"highlightwords.defaultMode": 1,` instead.

However, the config is still NOT loaded when vscode is started. It is only applied only on configuration update. (do any valid change to the config file and save)

**Comment by rsbondi** [comment]
thanks, 560166b8c8570d5ae7bc1602beaa1e8640d5fbd4, not sure when I will deploy

**Comment by rsbondi** [comment]
published
