### ISSUE TITLE
Allow configuring the text colour when using a dark theme with box.dark: false

### ISSUE THREAD

**Issue by AndrioCelos** [rsbondi/highlight-words#13]
I am currently experimenting with background colours with dark themes, but have run into the problem that the colour is either too bright or may make the hard-coded text colour `#555555` hard to read.
![image](https://user-images.githubusercontent.com/6897624/55610663-24dfbc00-57cf-11e9-9bb7-a63a6aa63244.png)
I'd like to suggest a config option be added to suppress the hard-coded colour or allow it to be changed.
Thank you for this extension; I found it quite useful.

**Comment by rsbondi** [comment]
is the `highlightwords.colors` setting not working for you?
