### ISSUE TITLE
count how many occurrences

### ISSUE THREAD

**Issue by ucavalcante** [rsbondi/highlight-words#15]
Will be great if in front of occurrence have a counter with hit count like 1/x for navigation.

tks for your work for communit.

**Comment by rsbondi** [comment]
Thanks for the suggestion.  Do you mean in the status bar? Or in the explorer?  I think this could be useful, just not sure how to represent.

**Comment by ucavalcante** [comment]
i think in explorer will be better.

**Comment by rsbondi** [comment]
https://github.com/rsbondi/highlight-words/commit/0f0909fbcb00633170b5128d890131eca3c0f645

**Comment by rsbondi** [comment]
published
