### ISSUE TITLE
Could you please add a function that can auto detect  a word is highlighting or not !

### ISSUE THREAD

**Issue by heartacker** [rsbondi/highlight-words#16]
some time I just want to toggle highlight that word within one Shortcut key

thanks

**Comment by rsbondi** [comment]
c9bdaef100bef1a94357305f668e79677a1cf366

**Comment by rsdenijs** [comment]
this is not released to vscode yet, right?

**Comment by rsbondi** [comment]
No. Probably end of month deployment.

**Comment by rsbondi** [comment]
published
