### ISSUE TITLE
Highlight on select

### ISSUE THREAD

**Issue by kenijo** [rsbondi/highlight-words#17]
Could you had the option to highlight on mouse select? And remove highlight when selection is unselected.

**Comment by rsbondi** [comment]
Thank you for your input.  This sound like the default vscode visual, of course without the options, or included in the tree, not sure I see the benefit, unless I am missing something?

**Comment by kenijo** [comment]
I was thinking of activating the "Highlight Toggle Current" on mouse select so that it highlights all the instances of the selected word in the file and across multiple panels.

I don't believe this is a default behavior of VSCode unless there is an option to activate that I missed.

**Comment by lonix1** [comment]
Agreed, until this is [included in vscode](https://github.com/microsoft/vscode/issues/87274), it would be a great feature for this plugin.

i.e. highlight word in all panels.

**Comment by kenijo** [comment]
As far as I understand, this now a VS Code feature under the option:

- "editor.occurrencesHighlight": "off"
- "editor.occurrencesHighlight": "singleFile"
- "editor.occurrencesHighlight": "multiFile"
