### ISSUE TITLE
one issue on partial highlight

### ISSUE THREAD

**Issue by shouwei** [rsbondi/highlight-words#18]
Hi,
I am a big fan of this plugin since it provides me exactly the same feature as Source Insight highlight.
I found an issue as follows:

    void remove(int i);
    void remove(int i, int n);
    inline void removeFirst() { Q_ASSERT(!isEmpty()); erase(d->begin()); }
    inline void removeLast();

when we want to highlight remove, removeFirst and removeLast also got highlighted partially. For most programmers, this is unexpected behavior. Because it's normal that two variables have some common part in their names. 

Could you please try to fix this issue?

**Comment by rsbondi** [comment]
Use `Highlight Selection with Options` and select `whole word`

To use whole word as default set in your configuration

`highlightwords.defaultMode` to `1`

**Comment by rsbondi** [comment]
Closing, will reopen if this was not the satisfactory answer
