### ISSUE TITLE
dont work with VSC 1.13.0

### ISSUE THREAD

**Issue by yummta** [rsbondi/highlight-words#2]
I just updated version 1.13.0 and it has stopped working. I reinstalled the extension and it does not work either

**Comment by rsbondi** [comment]
Thanks for reporting, it seems to work with light theme but not dark, I will update shortly

**Comment by rsbondi** [comment]
I have opened https://github.com/Microsoft/vscode/issues/28377, if I do not see a response I will change the dark themes to use background instead of border, but I really like the border and would like to keep it.  It is difficult to get a good color set for background highlights with dark themes.

**Comment by rumit91** [comment]
Looks like VS Code devs said that the workaround is to always set border-color. Would that solve this issue? I love this plugin and would love to have the full functionality back! Thanks for creating and maintaining it!

**Comment by rsbondi** [comment]
They made the [patch](https://github.com/Microsoft/vscode/commit/e7f7f423a5fe3680fba6bed5f5e2b78d99037f4b), looks like they were talking about internal "workaround" but not sure that is the correct word, it should be out in the next vscode release early July

**Comment by rsbondi** [comment]
API is fixed in latest vscode release.
