### ISSUE TITLE
is there a option to math the whole word but a part of word?

### ISSUE THREAD

**Issue by kuhnliu** [rsbondi/highlight-words#20]
Sometimes,  i want to highlight a variable eg. 'Number', and maybe there is another function named 'GetNumber()', but i don't want to highlight a part of GetNumber. Is there a option to control this behavior?

**Comment by rsbondi** [comment]
You can either from the command pallet choose "Highlight Selection with Options"  or in config change the default 

```
"highlightwords.defaultMode": {
    "default": 1
}
```

You can also change the option after it is selected from the Highlights section of the tree, right click on the word and select "Change Options"
