### ISSUE TITLE
setting foreground color 

### ISSUE THREAD

**Issue by gqst** [rsbondi/highlight-words#22]
After the code is highlighted, it is easy to be confused with the background color of the plug-in, resulting in unclear.

I think it would be very helpful if the foreground color can be customized.

example：
![image](https://user-images.githubusercontent.com/25261055/90224849-e89c8100-de42-11ea-96c5-cc656450d1e6.png)

**Comment by rsbondi** [comment]
What theme are you using?  vscode version? I can not duplicate, it seems the editor automatically updates the foreground.  Background colors are configurable with `highlightwords.colors` so you could maybe find better matching colors for you theme.  Also, you could set `highlightwords.box` to `true` for `dark`

**Comment by gqst** [comment]
I am using the default build-in color theme: Dark + (default dark). 
vscode version:  1.48.0

can try highlighting on white words:
![image](https://user-images.githubusercontent.com/25261055/90375081-066a2000-e0a7-11ea-9546-62c013b14cf2.png)

It appears that the plugin does not change the original color of the font (foreground color).  It will be unclear if the original font color is similar to the highlighted color (highlightwords.color). And, it is troublesome to adapt highlightwords.colors specifically for different themes.

A little advice, it may be better if the plugin could just set the highlighted foreground color to black.
Here is a vim plugin with  same function --- 'Inkarkat/Vim-Mark'. As shown below, the display is more friendly.

![image](https://user-images.githubusercontent.com/25261055/90375512-a4f68100-e0a7-11ea-94d3-bf89cc9fcf50.png)

**Comment by rsbondi** [comment]
Thanks for the additional information.  I get a dark gray foreground, regardless of the syntax highlighting, with that, or any theme, there may be conflicting setting causing this behavior, or maybe it is OS specific.  What is your OS?  If there is nothing confidential, could you post the settings.json, user and workspace?  Or maybe there is another extension you are using that may be conflicting.  Yours seems to be preserving the syntax highlighting, If I can duplicate, then I could explore possible solutions.

![highlight](https://user-images.githubusercontent.com/3729091/90402771-90919480-e065-11ea-8b0c-82c65d11271c.png)

**Comment by gqst** [comment]
I removed all other highlight plugins, and now it works as expected. I think I made a mistake about the shortcut key, sorry to trouble you....orz
