### ISSUE TITLE
Configuration.defaultMode issue in vscode setting.json

### ISSUE THREAD

**Issue by luckzylp** [rsbondi/highlight-words#23]
Hello,

Setting highlightwords.defaultMode to 1 (whole word) in setting.json does not work. Is there any way that can fix this? Thanks.
My current version of vscode running environment is as follows:
highlight-words version: v0.1.4
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0 
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by rsbondi** [comment]
Thanks, I am not on windows.  I get the same vscode values on about screen except for OS and same extension version.  It is working in my setup.  Did this recently stop working?  Do you have any other extensions that may be conflicting?

**Comment by luckzylp** [comment]
Hello rsbondi,

Thanks for your reply. I can understand the difference in OS. For me, rsbondi.highlight-words is the best extension for highlight.
On my computer, "highlightwords.defaultMode" has not worked normally in the setting.json of vscode, but the other configuration options of "highlightwords.colors", "highlightwords.box", and "highlightwords.showSidebar" are all normal work.
For the problem of extensions conflicts, I made an attempt, deleted all the extensions  of vscode, and only installed rsbondi.highlight-words, this configuration "highlightwords.defaultMode": {
"default": 1
}, still failed to take effect. So I think this problem is not a extensions conflict.

It is worth mentioning that although the "highlightwords.defaultMode" cannot take effect in the setting.json configuration of vscode, you can use the shortcut key Ctrl + Shift + P to set Set Highlight Mode = Whole Word, which works normally and meets expectations . The configuration of my rsbondi.highlight-words in setting.json is as follows:
	"highlightwords.colors": [
		{ "light": "#b3d9ff", "dark": "yellow" },
		{ "light": "#b3d9ff", "dark": "cyan" },
		{ "light": "#e6ffb3", "dark": "pink" },
		{ "light": "#b3b3ff", "dark": "lightgreen" },
		{ "light": "#ffd9b3", "dark": "magenta" },
		{ "light": "#ffb3ff", "dark": "cornflowerblue" },
		{ "light": "#b3ffb3", "dark": "orange" },
		{ "light": "#ffff80", "dark": "green" },
		{ "light": "#d1e0e0", "dark": "red" }                                        
	],
	"highlightwords.box": {
		"light": false,
		"dark": false
	},
	"highlightwords.showSidebar": {
		"default": true
	},
	"highlightwords.defaultMode": {
		"default": 1
	},

**Comment by rsbondi** [comment]
it should be`"highlightwords.defaultMode": 1`, what is shown there is the contribution, the `default` is the default value, or what is used if nothing is set, but the setting file does not include it, it is probably confusing in the documentation.

**Comment by luckzylp** [comment]
Using the configuration of ""highlightwords.defaultMode": 1", it works good on on both the windows platform and the linux platform. As you said, my understanding of the document is incorrect. Thank you very much for your support and help. I will close this  issue. Thanks.
