### ISSUE TITLE
Configurable colors & highlight current word & highlight background

### ISSUE THREAD

**Issue by balta2ar** [rsbondi/highlight-words#4]
Hello! First of all, thank you for the very useful extension! On vim I used Marks (http://www.vim.org/scripts/script.php?script_id=2666) and I missed similar functionality a lot on VSCode. Now to the point:

1. Configurable colors. Could you please add an option so that user could specify custom colors? I wish I could add custom palette generated, for example, with colorbrewer. Here it's important to use all colors the user has provided. For example, if there are 30 colors, please don't limit colorization to 8 internal colors provided by default.

2. Add "Highlight current word" command. It's nice to have "Highlight selection" but I also miss a simpler version of it. In vim it was very handy to walk over variables in a function and highlight several of them pressing just one button (well, two actually in my case: `,m`). I'd like to add a shortcut to this action when it's there. I think it also could be useful to have a configuration to what's a "word". Maybe a regexp for word separators or something similar. I'd like to have a similar action for "Remove all". At this moment I can do it but I need to choose my action in the menu. Is there a way to configure it without touching the mouse, just remove by a single command?

3. Instead of adding a rectangular box, maybe you could alternatively fill the box and invert the text color or make it black, i.e. highlight using background. Here is how it looks in vim:

![](http://scrin.org/i/17/07/tmpgmzdlggb7us.png)

Thank you!

**Comment by rsbondi** [comment]
1.  Should be simple
2.  Sounds useful but not sure about making what a word is configurable.  that should be determined by the language, see description at [TextDocument.](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextDocument).getWordRangeAtPosition
3. Item 1 would cover this.  I am using the background on light themes, I could not easily come up with a color set that looked good on dark themes, but I have not tried changing the foreground color, thanks for the suggestion(also I could not come up with a good color set using boxes for light themes)

**Comment by balta2ar** [comment]
> At this moment I can do it but I need to choose my action in the menu. Is there a way to configure it without touching the mouse, just remove by a single command?

What about this? Is there a way in VSCode to assign a shortcut to a command with an option without showing the menu? If it's possible, a separate command is not needed, I just don't know how to do it.

**Comment by rsbondi** [comment]
I suppose I could separate out the commands for remove and keep the 2 step for backward compatibility.

**Comment by rsbondi** [comment]
This has been published with the exception of "Highlight current word" command, will consider for a future release

**Comment by rsbondi** [comment]
I published changing the `highlightwords.addHighlight` command to use word at cursor if nothing selected, so no new command, just changed in menu to "Highlight Current"
