### ISSUE TITLE
Remove all on close

### ISSUE THREAD

**Issue by hugows** [rsbondi/highlight-words#6]
HI rsbonidi,

love your extension - I had something similar in Emacs and Sublime and use it all the time to review code quickly.
A configuration I miss: if highlights could be removed when the window/file is closed. This wuold be an easier way to "remove all" :)

Thanks for this!

**Comment by rsbondi** [comment]
The highlights span all files in the vscode instance, this is desirable for example looking at store or pubsub messages between components, so not sure, are the other editor's highlights per file?  When a window is opened, highlights are not preserved so closing a window effectively removes them.

**Comment by hugows** [comment]
Agreed, thanks.
