### ISSUE TITLE
Highlight whole word by default?

### ISSUE THREAD

**Issue by mitliao** [rsbondi/highlight-words#8]
Can you add highlight "whole word" by default as an option or settings? Right now it seems that I can only highlight whole word by selecting highlight selection with options every time.

**Comment by rsbondi** [comment]
Sounds like a reasonable request. Maybe there needs to be a highlight mode command added so you could go back. Not sure when I will have time to work on it but sounds good, thanks.

**Comment by rsbondi** [comment]
This update has been published to marketplace
